load("@io_bazel_rules_go//go:def.bzl", "go_library")  # noqa

# go_library(  # noqa
#     name="go_default_library",
#     srcs=[
#         "???",
#     ],
#     deps=[
#     ],
#     importpath="github.com/dr4ke616/grpc-test/server",
#     visibility=["//visibility:public"],
# )
