load("@io_bazel_rules_go//go:def.bzl", "go_library")  # noqa

go_library(  # noqa
    name="client",
    srcs=[
        "hello_world_client.go",
    ],
    deps=[
    ],
    importpath="github.com/dr4ke616/grpc-test/client",
    visibility=["//visibility:public"],
)
